version: "3.3"
services:

  node:
    image: node:16-alpine
    container_name: mediacube-ui-node
    working_dir: /app
    environment:
      - NODE_ENV=local
    volumes:
      - ./:/app
    command: "tail -f /dev/null"
    ports:
      - 9000:9000

networks:
  default:
    external:
      name: mediacube-network